//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KineticValidator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastProjectFolder {
            get {
                return ((string)(this["LastProjectFolder"]));
            }
            set {
                this["LastProjectFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SkipSchemaErrors {
            get {
                return ((bool)(this["SkipSchemaErrors"]));
            }
            set {
                this["SkipSchemaErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReformatJson {
            get {
                return ((bool)(this["ReformatJson"]));
            }
            set {
                this["ReformatJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"%value%; %row%; %oldValue%; %current%; %previous%; %column%; %currentDataView%; %previousDataView%; %coreCurrentDataView%; %corePreviousDataView%; %nodeEntityType%; %nodeSysRowID%; %nodeIsFolder%; %dragEntityType%; %startDateTime%; %endDateTime%; %isAllDayEvent%; %viewName%")]
        public string SystemMacros {
            get {
                return ((string)(this["SystemMacros"]));
            }
            set {
                this["SystemMacros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("context;Constant;CallContextBpmData;CallContextClientData;actionResult;searchResu" +
            "lt;sysLicensedModules;sysTools;sysGlobalVariable;sysPages;sysTabs;sysVariable;sy" +
            "sTreeNode;sysDragRows;sysPublishedData;strings;sysGanttTasks;")]
        public string SystemDataViews {
            get {
                return ((string)(this["SystemDataViews"]));
            }
            set {
                this["SystemDataViews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dataviews.jsonc;events.jsonc;layout.jsonc;rules.jsonc;tools.jsonc;strings.jsonc;p" +
            "atch.jsonc")]
        public string InitialProjectFiles {
            get {
                return ((string)(this["InitialProjectFiles"]));
            }
            set {
                this["InitialProjectFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ArrayItemNotValid;PropertyRequired;NoAdditionalPropertiesAllowed")]
        public string IgnoreSchemaErrors {
            get {
                return ((string)(this["IgnoreSchemaErrors"]));
            }
            set {
                this["IgnoreSchemaErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowPositionX {
            get {
                return ((int)(this["MainWindowPositionX"]));
            }
            set {
                this["MainWindowPositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowPositionY {
            get {
                return ((int)(this["MainWindowPositionY"]));
            }
            set {
                this["MainWindowPositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowWidth {
            get {
                return ((int)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowHeight {
            get {
                return ((int)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Editor1PositionX {
            get {
                return ((int)(this["Editor1PositionX"]));
            }
            set {
                this["Editor1PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Editor1PositionY {
            get {
                return ((int)(this["Editor1PositionY"]));
            }
            set {
                this["Editor1PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Editor1Width {
            get {
                return ((int)(this["Editor1Width"]));
            }
            set {
                this["Editor1Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Editor1Height {
            get {
                return ((int)(this["Editor1Height"]));
            }
            set {
                this["Editor1Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Editor2PositionX {
            get {
                return ((int)(this["Editor2PositionX"]));
            }
            set {
                this["Editor2PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Editor2PositionY {
            get {
                return ((int)(this["Editor2PositionY"]));
            }
            set {
                this["Editor2PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Editor2Width {
            get {
                return ((int)(this["Editor2Width"]));
            }
            set {
                this["Editor2Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Editor2Height {
            get {
                return ((int)(this["Editor2Height"]));
            }
            set {
                this["Editor2Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreHttpsError {
            get {
                return ((bool)(this["IgnoreHttpsError"]));
            }
            set {
                this["IgnoreHttpsError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SchemaValidation;RedundantFiles;ValidateFileChars2;DuplicateIds;EmptyPatchNames;RedundantPatches;CallNonExistingPatches;OverridingPatches;PatchAllFields;EmptyStringNames;EmptyStringValues;RedundantStrings;CallNonExistingStrings;OverridingStrings;EmptyEventNames;EmptyEvents;OverridingEvents;RedundantEvents;CallNonExistingEvents;EmptyDataViewNames;RedundantDataViews;CallNonExistingDataViews;OverridingDataViews;EmptyRuleNames;OverridingRules;EmptyToolNames;OverridingTools;MissingForms;MissingSearches;JsCode;JsDataViewCount;IncorrectLayoutIds")]
        public string EnabledValidators {
            get {
                return ((string)(this["EnabledValidators"]));
            }
            set {
                this["EnabledValidators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPreview {
            get {
                return ((bool)(this["ShowPreview"]));
            }
            set {
                this["ShowPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MessageColumnWidth {
            get {
                return ((int)(this["MessageColumnWidth"]));
            }
            set {
                this["MessageColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveTmpFiles {
            get {
                return ((bool)(this["SaveTmpFiles"]));
            }
            set {
                this["SaveTmpFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveReport {
            get {
                return ((bool)(this["SaveReport"]));
            }
            set {
                this["SaveReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\_projects\\ERP\\Current\\Deployment\\Server\\Assemblies")]
        public string ServerAssembliesPath {
            get {
                return ((string)(this["ServerAssembliesPath"]));
            }
            set {
                this["ServerAssembliesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseVsCode {
            get {
                return ((bool)(this["UseVsCode"]));
            }
            set {
                this["UseVsCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplyPatches {
            get {
                return ((bool)(this["ApplyPatches"]));
            }
            set {
                this["ApplyPatches"] = value;
            }
        }
    }
}
