copy /Y C:\_projects\ERP\Current\Deployment\Server\Bin\Epicor.ServiceModel.deps.json .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Bin\Epicor.ServiceModel.dll .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Bin\Epicor.ServiceModel.pdb .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Bin\Epicor.ServiceModel.xml .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Erp.Common.ContractInterfaces.deps.json .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Erp.Common.ContractInterfaces.dll .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Erp.Common.ContractInterfaces.pdb .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Erp.Common.ContractInterfaces.xml .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Erp.Contracts.BO.JobEntry.deps.json .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Erp.Contracts.BO.JobEntry.dll .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Erp.Contracts.BO.JobEntry.pdb .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Erp.Contracts.BO.JobEntry.xml .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Ice.Contracts.Lib.ClassAttribute.deps.json .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Ice.Contracts.Lib.ClassAttribute.dll .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Ice.Contracts.Lib.ClassAttribute.pdb .
copy /Y C:\_projects\ERP\Current\Deployment\Server\Assemblies\Ice.Contracts.Lib.ClassAttribute.xml .
